### ISSUE TITLE
Reset stats using command line

### ISSUE THREAD

**Issue by maggaou** [MeineZ/BMDemoTouchRatio#11]
Offer command like demotouchcount_reset_stats that can be used in key bindins. Reset only current session. 

This can be useful in training and/or when playing different game modes. Obviously game mode specific stats would be great (you can make issue for that).

**Comment by MeineZ** [comment]
Added this, but ran out of time to properly test. Will do that at a later time.

**Comment by MeineZ** [comment]
'cl_demotouch_plugin_reset_stats' is the command you can bind to a key!

Once the update is approved, that is.

**Comment by MeineZ** [comment]
I also changed the plugin name from "Demo Touch Count" to "Simple Stats Tracker". Just figured to mention it here so you can find it in case you lost it :)
