### ISSUE TITLE
Boost usage

### ISSUE THREAD

**Issue by maggaou** [MeineZ/BMDemoTouchRatio#8]
Total boost used during match. Player and team based boost usage stats.

**Comment by MeineZ** [comment]
Nice one, thanks for your input!
I will consider adding this in the next update. This thread will keep you uptodate.

Thing is, not all information of your car is available (e.g., your speed/velocity). So, I'll have to check if this data is even available to track. I believe I have seen some plugins that show current boost, so I have a good feeling about it. Nonetheless, I'll still have to validate it.

Also, question: What do you mean with team based boost? I'm pretty certain that bakkesmod plugins cannot track the boost meter of other players in the lobby, so the team based stats is a no-go if that's what you mean.

**Comment by maggaou** [comment]
>Also, question: What do you mean with team based boost? I'm pretty certain that bakkesmod plugins cannot track the boost meter of other players in the lobby, so the team based stats is a no-go if that's what you mean.

Yes sorry. Obviously plugins cannot read inputs of other players in real time. Let's hope you come up with a solution how to read self input. As with ball hits/demos it would be cool to compare current boost usage to previous/global stat. Maybe boost-per-minute would be the most relevant stat. We can compare boost as a function of time but choosing exact time points like boost1(5.5) and boost2(5.5) isn't very interesting. On the other hand we can calculate things from t = 0 to t = current time like:

$$ \sum_{t = 0}^{t_f} \left| b_1(t) - b_2(t) \right| $$

- same formula but replace $b$ (cumulative boost) with boost-per-unit-time (rate of change of $b$)
- I'm not sure if these two are correlated
- real time graph of current boost-per-unit-time with corresponding previous graph would be cool and informative
- taking logarithm of the cumulative graph and comparing these graphs may look cleaner

**Comment by MeineZ** [comment]
Right, I'm probably able to implement both boost-per-minute and total boost used.

Again, I'll have to investigate, but I'll keep you uptodate in this thread. Not sure when I'll get to this though, probably in the weekends.

**Comment by MeineZ** [comment]
Pushed boost tracking to `origin/main`. Currently uploading it to bakkesplugins.com. When that's done, it'll have to wait for someone to approve the update. Will let you know in this thread when it's online!
