### ISSUE TITLE
In air %

### ISSUE THREAD

**Issue by maggaou** [MeineZ/BMDemoTouchRatio#9]
Time spent in air, measured in %. Example: 40% means player spent 40% of the time in air. Player and team based stats.

**Comment by MeineZ** [comment]
I'll take a look at this! This thread will keep you uptodate.

Thing is, just like your other feature request #8, you cannot read much data from other players in the lobby with bakkesmod plugins, including their positions (to check if they are in the air). There may be a work around though, I'll have to investigate.

Also, same question as in the other thread: What do you mean with team based stats? I'm pretty certain that bakkesmod plugins cannot track the boost meter of other players in the lobby, so the team based stats is a no-go if that's what you mean.

**Comment by MeineZ** [comment]
Got one thing left to do here: Add behaviour manipulation.

This allows for setting a delay for in-air detection. E.g. only detect that the player is in the air after one second that the player actually got in the air.

**Comment by maggaou** [comment]
Not bad idea but I think zero-delay and non-zero aerial % are linearly
correlated. Maybe we find that out later.

ti 31. tammik. 2023 klo 20.40 Meine Zeinstra ***@***.***)
kirjoitti:

**Comment by MeineZ** [comment]
Yeah, I think they are. I just want to add custom behaviour to most ofthe stats as thats one of the features this plugin offers.

I dont think it matters though, its just there for the player to say: If I was in the air for less then, for example, 0.5 seconds, I don't want to count it as an aerial
